### ISSUE TITLE
100Mbits limit

### ISSUE THREAD

**Issue by yshiro** [LightningMods/Store-CDN-Tool#10]
Hi, first of all thanks for all your efforts! 

I don´t know if can be related to the app, but my computer are sending to a fixed speed of 100Mbits
![image](https://github.com/LightningMods/Store-CDN-Tool/assets/32700990/d8188d18-971e-4507-9b5b-5fbbd03aab29)

I´ve verified both devices PC & PS5 are linking at 1Gb on the switch. 

There is any setting that can be modified related to the network throttle or similar?

Regards

**Comment by LightningMods** [comment]
Hello, try recompiling with a higher buffer size here https://github.com/LightningMods/Store-CDN-Tool/blob/d04311983dd1ff0ba8e898300d61967382043773/Form1.cs#L436 and if you haven't already try setting the temp path in settings to your USB if neither help try using the NFS option in itemzflow which should give faster speeds
