### ISSUE TITLE
Network Path on Package Page Has a Typo

### ISSUE THREAD

**Issue by AwesomeAustn** [LightningMods/Store-CDN-Tool#2]
The server app finds the packages, and lists them in the Store, but the path is modified on the package page, and won't download. It removes the first letter after \

Example:
Sever app path:
\\UNRAID\Games

Package page in the Store:
http://IP/NRAID/Game.pkg

**Comment by LightningMods** [comment]
We are working to resolve this bug.

**Comment by LightningMods** [comment]
Hello, we are testing a fix in our discord if you want to try it too

https://discord.gg/4dwNQbev

**Comment by LightningMods** [comment]
It's now been added, see the releases section
