### ISSUE TITLE
[Enhancement] Please, LINUX

### ISSUE THREAD

**Issue by pepitopajas** [LightningMods/Store-CDN-Tool#3]
Hello, I would like this same application but in linux

**Comment by LightningMods** [comment]
Hello, we want to make a Linux version soon,
Remember the best way to show support for this program is to donate via [Ko-fi](https://ko-fi.com/lightningmods)

**Comment by pepitopajas** [comment]
> Hello, we want to make a Linux version soon, Remember the best way to show support for this program is to donate via [Ko-fi](https://ko-fi.com/lightningmods)

**Comment by pepitopajas** [comment]
oK, Ko-fi . Hello, I have tried with wine in linux, and it works perfectly
